# Generated by Django 3.0.5 on 2020-04-10 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_brand_company_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='premium_table',
            name='premium',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='premium_table',
            name='revenue_stamp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='premium_table',
            name='total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='premium_table',
            name='vat',
            field=models.FloatField(default=0.0),
        ),
    ]
