# Generated by Django 3.0.5 on 2020-04-10 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200410_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='person',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='person',
            name='password',
        ),
        migrations.RemoveField(
            model_name='person',
            name='username',
        ),
    ]
