# Generated by Django 3.0.5 on 2020-04-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200410_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium_table',
            name='make_model',
            field=models.CharField(max_length=255),
        ),
    ]
