# Generated by Django 3.0.4 on 2020-04-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200424_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='picture',
            field=models.CharField(default='https://i.stack.imgur.com/l60Hf.png', max_length=255),
        ),
    ]
