# Generated by Django 3.0.4 on 2020-04-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_company_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='picture',
            field=models.CharField(default='https://i.stack.imgur.com/l60Hf.png', max_length=255),
        ),
    ]
