# Generated by Django 3.0.5 on 2020-04-11 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_auto_20200410_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_on', models.CharField(max_length=7)),
                ('date_register', models.DateField()),
                ('model', models.CharField(max_length=255)),
                ('chassis_on', models.CharField(max_length=17)),
                ('displacement', models.IntegerField()),
                ('gvw', models.IntegerField()),
                ('seat', models.IntegerField()),
                ('type', models.CharField(choices=[('a', 'รถยนต์'), ('b', 'จักรยานยนต์')], max_length=12)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField()),
                ('status', models.CharField(choices=[('av', 'available'), ('uv', 'unavailable')], max_length=11)),
                ('date_start_cover', models.DateField()),
                ('date_end_cover', models.DateField()),
                ('price', models.FloatField(default=0.0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.Car')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=13)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance_Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_id', models.CharField(max_length=25)),
                ('insurance_code', models.CharField(choices=[('a', '1'), ('b', '2'), ('c', '3'), ('d', '3+')], max_length=2)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.Contract')),
                ('insurance_car_use_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Car_Use_Type_Table')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=13)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Person')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.Customer'),
        ),
        migrations.CreateModel(
            name='Compulsory_Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compulsory_id', models.CharField(max_length=25)),
                ('compulsory_car_use_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Premium_Table')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.Contract')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.Owner'),
        ),
        migrations.AddField(
            model_name='car',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Province'),
        ),
    ]
