# Generated by Django 3.0.5 on 2020-04-13 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200410_1405'),
        ('contract', '0002_auto_20200413_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('รถยนต์', 'รถยนต์'), ('รถจักรยานยนต์', 'จักรยานยนต์')], max_length=13),
        ),
        migrations.AlterField(
            model_name='compulsory_insurance',
            name='compulsory_car_use_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Premium_Table'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=11),
        ),
        migrations.AlterField(
            model_name='customer',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Person'),
        ),
        migrations.AlterField(
            model_name='insurance_policy',
            name='insurance_car_use_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Car_Use_Type_Table'),
        ),
        migrations.AlterField(
            model_name='insurance_policy',
            name='insurance_code',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('3+', '3+')], max_length=5),
        ),
    ]
