# Generated by Django 3.0.4 on 2020-04-25 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0009_auto_20200424_1011'),
        ('contract', '0013_auto_20200424_1615'),
    ]

    operations = [
    ]
