# Generated by Django 3.0.5 on 2020-04-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0020_auto_20200427_1928'),
        ('contract', '0018_auto_20200428_1350'),
    ]

    operations = [
    ]
