# Generated by Django 3.0.4 on 2020-04-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infocustomer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='picture',
            field=models.CharField(default='https://i.stack.imgur.com/l60Hf.png', max_length=255),
        ),
    ]
