# Generated by Django 3.0.4 on 2020-04-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infocustomer', '0003_auto_20200424_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_no', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
