# Generated by Django 3.0.4 on 2020-04-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infocustomer', '0005_seller_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='picture',
            field=models.CharField(default='https://i.stack.imgur.com/l60Hf.png', max_length=255),
        ),
    ]
