# Generated by Django 3.0.4 on 2020-04-25 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infocustomer', '0006_company_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
