# Generated by Django 3.0.4 on 2020-04-28 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infocustomer', '0007_delete_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
