# Generated by Django 3.0.4 on 2020-04-28 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infocustomer', '0008_delete_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
